name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup BATS testing framework
      uses: mig4/setup-bats@v1.2.0
    - name: Test with BATS
      run: bats test.bats